### ISSUE TITLE
Scrolling doesn't work on long lists

### ISSUE THREAD

**Issue by sfarmani** [Xhylo/Visual-Studio-Code-BD-theme#14]
I've noticed that scrolling on long lists such as the members list for a server or list of open DMs, it stops scrolling after a bit. It won't scroll back up either, I have to change channels for it to reset.

**Comment by Xhylo** [comment]
Hello, I will surely take a look into that issue you've made, I'm currently unavailable, so I'll look into it when I can.

~ Xyhlo

**Comment by lolpowerluke** [comment]
how long am I supposed to scroll before the issue appears?
cause I tried scrolling through the memberlist of the betterdiscord server for a while, but I dont get that issue

**Comment by sfarmani** [comment]
I tried it too on the powercord discord member list, however I believe that member list is not a good example as it seems to be constantly updating (members going offline and online), so the scrolling refreshes

I would suggest doing it on a list of open DMs as it does get stuck there. It doesn't take long to get stuck. It is a bit volatile so it doesn't always get stuck right away.... its a strange issue :/ I don't know how else to explain

**Comment by lolpowerluke** [comment]
does it completely stop or does it work again if you wait a few seconds? 
cause I had the same on powercord with a long list, but after waiting a few seconds it was fine again

**Comment by sfarmani** [comment]
yeah it starts working again after a few seconds (yesterday it was a couple of seconds, but today its like 30 or so seconds...). At the time I made this issue, it wouldn't start again and to force it to work, I would either have to switch guilds to refresh or use the middle mouse button click and drag to scroll.

I guess somethings to note that I didn't quite mention in my first post:
I tried this on vanilla discord, then on powercord without this theme, and they both didn't have any issues with scrolling.
Once I turn on the theme, it starts to have issues.

**Comment by lolpowerluke** [comment]
`.scrolling-1Cdwk- .content-3YMskv {
  pointer-events: all;
}`
does this help? (for the member list)

**Comment by sfarmani** [comment]
No, it still gets stuck

**Comment by lolpowerluke** [comment]
Do you have any other css enabled?
And which plugins do you have?

**Comment by sfarmani** [comment]
I don't have any other CSS enabled, just yours and i've added my own changes
But whenever I am testing it for you, I am reverting my changes so that it purely has your changes involved.

here is a list of plugins i have enabled

Better Codeblocks
Message Translate
petpet
PinDMs
Plugin Downloader
Remind Me
Theme Downloader

I do want to reinstate this part:

> I tried this on vanilla discord, then on powercord without this theme, and they both didn't have any issues with scrolling.
Once I turn on the theme, it starts to have issues.

**Comment by lolpowerluke** [comment]
![image](https://user-images.githubusercontent.com/47672899/143765106-a0677ba2-2376-4d00-a877-0d5a61ea3892.png)
delete this
found that this fixes it after searching for like 1 hour

**Comment by lolpowerluke** [comment]
I'll probably make a pr to fix this for other people to
