### ISSUE TITLE
Search results cover messages

### ISSUE THREAD

**Issue by Guest257351** [Xhylo/Visual-Studio-Code-BD-theme#18]
After making a search the search results box covers messages.

How to replicate: search for messages

How to fix: make the search results box push the messages box to the right when it is open so they are both visible.

**Comment by lolpowerluke** [comment]
should be fixed when xyhlo accepts this pr
#19

**Comment by Guest257351** [comment]
> should be fixed when xyhlo accepts this pr #19

Alright

**Comment by lolpowerluke** [comment]
can you close this issue if it was fixed?
