### ISSUE TITLE
Memberlist

### ISSUE THREAD

**Issue by EconomicSacks** [Xhylo/Visual-Studio-Code-BD-theme#2]
The animated memberlist is broken when you scroll up or down the memberlist. When you get to the top or bottom of the memberlist it bugs out.

**Comment by abstraverse** [comment]
Would be cool too have an option to switch back to the ,,normal" member list style as well, without it hiding

**Comment by Xhylo** [comment]
> Would be cool too have an option to switch back to the ,,normal" member list style as well, without it hiding

### Hello
Thanks for your suggestion it really sounds great, but it can only be done with ```Js```, which can't be done with the themes.
Themes are ```CSS``` only.
Sincerely

_~Xyhlo_

**Comment by Xhylo** [comment]
> The animated memberlist is broken when you scroll up or down the memberlist. When you get to the top or bottom of the memberlist it bugs out.

### Hello
I just noticed the bug and implemented a fix for it, it should be fixed when the update pushes trough on the website.
Sincerely

_~Xyhlo_
