### ISSUE TITLE
Button to upload files on the bottom left is not there. 

### ISSUE THREAD

**Issue by Xemacs64** [Xhylo/Visual-Studio-Code-BD-theme#21]
![Screenshot_20230227_033952](https://user-images.githubusercontent.com/119147461/221692017-45796b7b-7eef-46b4-be4a-90ca47fa045f.png)
![Screenshot_20230227_034027](https://user-images.githubusercontent.com/119147461/221692032-06e6017a-b84e-4541-afe1-dc8361001e56.png)

**Comment by Xhylo** [comment]
You drag the nescessary files in, without the button.

**Comment by Xemacs64** [comment]
> You drag the nescessary files in, without the button.

oh okay thanks! why do you choose not to have a button to upload files?

**Comment by Xhylo** [comment]
To leave out junk, less clutter the better, either way I think you press <enter> to send messages and stuff, so that works like that with drag, enter etc.
