### ISSUE TITLE
Not compatible with CustomStatusPresets

### ISSUE THREAD

**Issue by CODExNEAT** [Xhylo/Visual-Studio-Code-BD-theme#3]
I'm using VSC Cord and it isn't compatible with the CustomStatusPresets. As shown in the attached screenshot it does not show the text I added to the status and the actual online status, only when it clears and the emote.
![unknown](https://user-images.githubusercontent.com/48189789/125190579-6f153a80-e22d-11eb-9805-10661569d10e.png)

**Comment by EconomicSacks** [comment]
I have confirmed this is also happening to me

**Comment by Xhylo** [comment]
> I'm using VSC Cord and it isn't compatible with the CustomStatusPresets. As shown in the attached screenshot it does not show the text I added to the status and the actual online status, only when it clears and the emote.
> ![unknown](https://user-images.githubusercontent.com/48189789/125190579-6f153a80-e22d-11eb-9805-10661569d10e.png)

### Hello
Yes, I have looked into it and it surely is not working, as I am not available to get on the pc/project till august of 20th it'll be like that. I am planning to add/fix stuff like that in the theme's development near the future.
Sincerely 

_~Xyhlo_
