### ISSUE TITLE
The theme breaks in macOS

### ISSUE THREAD

**Issue by CodeDiseaseDev** [Xhylo/Visual-Studio-Code-BD-theme#6]
<img width="518" alt="Screen Shot 2021-08-10 at 12 46 08 pm" src="https://user-images.githubusercontent.com/70626250/128800558-9b917efc-800c-4704-96af-4a96d904a70b.png">

**Comment by Xhylo** [comment]
Yeah, I see that's an issue, heard complaints from others, as I do not have a MacOS, I can't tell if it supports other operating systems besides Windows, which in this case it seems like, no unfortunately I will try and see if my fellow contributor will be able to assist in this case.

**Comment by Xhylo** [comment]
Fixed
