### ISSUE TITLE
Scrolling through the results after using the Search function does not work

### ISSUE THREAD

**Issue by abstraverse** [Xhylo/Visual-Studio-Code-BD-theme#9]
Hello, i believe i have found a bug. I tried disabling plugins so i do not think it is plugin related.
When searching for something in a DM/Server, you cannot scroll through the list with results.
![image](https://user-images.githubusercontent.com/75224771/129002950-da5a2a9e-7cfb-4413-83aa-187b971ae46d.png)

**Comment by Xhylo** [comment]
Yeah I will fix that, it's been there for a while, just haven't had the time to fix it because I work from 8AM till 9PM and I got no time.

**Comment by Xhylo** [comment]
Fixed.
